export const events = [
  {
    id: 1,
    title: 'Pet Adoption Fair',
    date: '2025-09-10',
    location: 'Dhaka, Bangladesh',
    description: 'A community fair to help dogs and cats find new homes.',
    image_url: 'https://i.ibb.co/1K0r8yN/pet-adoption.jpg',
  },
  {
    id: 2,
    title: 'Free Vet Camp',
    date: '2025-09-15',
    location: 'Chittagong, Bangladesh',
    description: 'Free health check-ups and vaccinations for stray pets.',
    image_url: 'https://i.ibb.co/F0L6xNz/vet-camp.jpg',
  },
  {
    id: 3,
    title: 'Dog Training Workshop',
    date: '2025-09-18',
    location: 'Sylhet, Bangladesh',
    description: 'Learn basic obedience and training tips for your pets.',
    image_url: 'https://i.ibb.co/DVZ5PvR/dog-training.jpg',
  },
  {
    id: 4,
    title: 'Pet Nutrition Seminar',
    date: '2025-09-20',
    location: 'Rajshahi, Bangladesh',
    description: 'Seminar on healthy diets and nutrition for pets.',
    image_url: 'https://i.ibb.co/N2qF1jC/pet-nutrition.jpg',
  },
  {
    id: 5,
    title: 'Adopt a Cat Day',
    date: '2025-09-22',
    location: 'Khulna, Bangladesh',
    description: 'Special adoption drive for homeless cats.',
    image_url: 'https://i.ibb.co/hYzScgV/cat-adoption.jpg',
  },
  {
    id: 6,
    title: 'Animal Welfare Talk',
    date: '2025-09-25',
    location: 'Barishal, Bangladesh',
    description: 'Awareness event on responsible pet ownership.',
    image_url: 'https://i.ibb.co/3rB2dQk/animal-welfare.jpg',
  },
  {
    id: 7,
    title: 'Fundraising Walk for Pets',
    date: '2025-09-27',
    location: 'Dhaka, Bangladesh',
    description: 'Join the charity walk to support pet shelters.',
    image_url: 'https://i.ibb.co/1JpFZjS/pet-walk.jpg',
  },
  {
    id: 8,
    title: 'Pet Grooming Workshop',
    date: '2025-09-29',
    location: 'Gazipur, Bangladesh',
    description: 'Learn professional grooming techniques for dogs & cats.',
    image_url: 'https://i.ibb.co/7nRSHrv/pet-grooming.jpg',
  },
  {
    id: 9,
    title: 'Stray Animal Rescue Meetup',
    date: '2025-10-02',
    location: 'Narayanganj, Bangladesh',
    description: 'Connect with volunteers working on stray rescues.',
    image_url: 'https://i.ibb.co/ScdT0rD/stray-rescue.jpg',
  },
  {
    id: 10,
    title: 'Pet Costume Contest',
    date: '2025-10-05',
    location: 'Dhaka, Bangladesh',
    description: 'Show off your pet’s cutest costumes and win prizes.',
    image_url: 'https://i.ibb.co/hRwncPg/pet-costume.jpg',
  },
  {
    id: 11,
    title: 'Pet Photography Day',
    date: '2025-10-08',
    location: 'Chattogram, Bangladesh',
    description: 'Free professional pet photography session.',
    image_url: 'https://i.ibb.co/dD8b5Ly/pet-photo.jpg',
  },
  {
    id: 12,
    title: 'Bird Lovers Gathering',
    date: '2025-10-10',
    location: 'Sylhet, Bangladesh',
    description: 'Event for bird lovers to share tips and adopt birds.',
    image_url: 'https://i.ibb.co/GdbRwK1/bird-event.jpg',
  },
  {
    id: 13,
    title: 'Pet Shelter Volunteering',
    date: '2025-10-12',
    location: 'Rajshahi, Bangladesh',
    description: 'Volunteer at a local animal shelter and help pets.',
    image_url: 'https://i.ibb.co/xfzFMWv/shelter-volunteer.jpg',
  },
  {
    id: 14,
    title: 'Dog Lovers Meetup',
    date: '2025-10-15',
    location: 'Dhaka, Bangladesh',
    description: 'A fun event for dog lovers and their furry friends.',
    image_url: 'https://i.ibb.co/ZmYp5Kt/dog-meetup.jpg',
  },
  {
    id: 15,
    title: 'Pet Adoption Rally',
    date: '2025-10-18',
    location: 'Khulna, Bangladesh',
    description: 'Rally to spread awareness about adopting pets.',
    image_url: 'https://i.ibb.co/L5xY7Vc/adoption-rally.jpg',
  },
  {
    id: 16,
    title: 'Vet Q&A Live Session',
    date: '2025-10-20',
    location: 'Barisal, Bangladesh',
    description: 'Ask your questions directly to a professional vet.',
    image_url: 'https://i.ibb.co/CbDnqM7/vet-qa.jpg',
  },
  {
    id: 17,
    title: 'Pet Fun Day',
    date: '2025-10-23',
    location: 'Sylhet, Bangladesh',
    description: 'Games and fun activities for pets and owners.',
    image_url: 'https://i.ibb.co/vqHkP3z/pet-funday.jpg',
  },
  {
    id: 18,
    title: 'Animal Rights Awareness',
    date: '2025-10-25',
    location: 'Dhaka, Bangladesh',
    description: 'Discussion on animal rights and welfare policies.',
    image_url: 'https://i.ibb.co/XF9DWsd/animal-rights.jpg',
  },
  {
    id: 19,
    title: 'Pet Product Expo',
    date: '2025-10-28',
    location: 'Gazipur, Bangladesh',
    description: 'Exhibition of pet food, toys, and accessories.',
    image_url: 'https://i.ibb.co/72Rfmgh/pet-expo.jpg',
  },
  {
    id: 20,
    title: 'Cat Cafe Meetup',
    date: '2025-10-30',
    location: 'Dhaka, Bangladesh',
    description: 'Meet cat lovers and enjoy coffee with furry friends.',
    image_url: 'https://i.ibb.co/YppCphk/cat-cafe.jpg',
  },
];
